name: Integration Test

on:
  push:
    branches-ignore:
      - '**-alpha'
      - '**-tmp'
      - '**-temp'
  pull_request:
    branches-ignore:
      - '**-alpha'
      - '**-tmp'
      - '**-temp'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          distribution: 'temurin'
      - name: Intergation Test
        run: mvn clean package -Pit-test -P!annotation-shade